### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kassane** [kassane/libvlc-zig#1]
This project is a small initial sample of VLC binding.
~~Initially the `zig translate-c` (`c` to `zig`) is not 100% yet, generating some inconsistencies in `vlc.h`. But `libvlc.h` is being translated in this example.~~

## Issues

- [x] fix `translate-c` on `vlc.h` - error: missing `struct_a`.
- [ ] ~~fix sleep timeout~~ *Upstream issue!*
- [ ] Tests
- [x] #2

## Examples

- [x] CLI - player
- [x] CLI - print version (libvlc, compiler)
- [ ] #3
- [ ] #5
- [x] #12

## Next steps

- [x] Build C and C++ examples w/ zig bindings
- [ ] Impl some abstractions mechanism
- [ ] Document zig binding.

cc: @tguillem

**Comment by kassane** [comment]
After I was able to run the example cli-player on Linux.

It is still necessary to investigate why `std.time.sleep` does not work as a timeout and requires using `c.sleep` from the system's native API.

**Comment by kassane** [comment]
After spending a few days trying to fix the CI/CD (Linux, MacOS), as for Windows, preferred to postpone it a little due to the interpretation complication (will review it more calmly later).

Now, refactoring the SDL_player example with OpenGL support.
Therefore, I take the opportunity to update Todo list for the next steps after merging the SDL2 example.

**Comment by kassane** [comment]
Windows CI (MinGW) issue has been fixed, and `cli-player` (zig version) example issue has been fixed and `cli-player` (c version) added. #11 
The implementation of the SDL will be resumed. #6
